# This allows Jenkins to deploy to the 'default' namespace using helm
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: jenkins-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create"]
- apiGroups: ["", "apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: jenkins-role-binding
subjects:
- kind: User
  name: jenkins
- kind: ServiceAccount
  name: default
  namespace: jenkins
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
- kind: ServiceAccount
  name: default
  namespace: default
- kind: ServiceAccount
  name: jenkins
  namespace: default
roleRef:
 kind: ClusterRole
 name: jenkins-role
 apiGroup: rbac.authorization.k8s.io
